### ISSUE TITLE
Can't send and receive sms with non-latin characters

### ISSUE THREAD

**Issue by kluchnikov** [nextgis/peoplefinder#103]
We should be able to send and receive sms in any language, but now only english (latin characters) is supported.
Osmo-nitb VTY command for sending sms supports only latin characters, beceause originally this command was implemented only for test purposes.
So osmo-nitb smpp interaface + kannel should be used for sending sms in any language instead of VTY command.

**Comment by simgislab** [comment]
@alisovenko please have a look and let @karavanjo know if changes on frontend are needed

**Comment by alisovenko** [comment]
Improved with https://github.com/nextgis/peoplefinder/commit/98324cfb186bcd01ae235f44ef08c08dc3fa9639
