### ISSUE TITLE
Implement send_sms endpoint

### ISSUE THREAD

**Issue by karavanjo** [nextgis/peoplefinder#21]
Type: POST

URL signature: imsi/{imsi}/message/send
POST parameters:
{body} - body of message

**Comment by karavanjo** [comment]
Response:
{status: 'sent'} - if sms was sent
{status: 'failed'} - if sms was'nt sent

**Comment by drnextgis** [comment]
https://github.com/nextgis/peoplefinder/commit/64cb90ce678e135f304985c5fa4fd9ff3129247f
