### ISSUE TITLE
Implement configuration page

### ISSUE THREAD

**Issue by simgislab** [nextgis/peoplefinder#59]
Should have the following settings:
1. Map for downloading tiles
2. Welcome message
3. IMSI update interval
4. SMS update interval
5. Silent SMS interval

**Comment by karavanjo** [comment]
Functionality for "Map for downloading tiles" was described in other issues - https://github.com/nextgis/peoplefinder/issues/38 and https://github.com/nextgis/peoplefinder/issues/37. 

Basic settings were added:
![image](https://cloud.githubusercontent.com/assets/669999/9471429/e5f3e7f4-4b58-11e5-9800-340b75147130.png)
